In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('./Microsoft_stock_data.csv', parse_dates=['Date'])

In [10]:
df.head()

        Date     Close      High       Low      Open      Volume
0 1986-03-13  0.059500  0.062157  0.054188  0.054188  1031788800
1 1986-03-14  0.061625  0.062688  0.059500  0.059500   308160000
2 1986-03-17  0.062688  0.063219  0.061625  0.061625   133171200
3 1986-03-18  0.061093  0.063219  0.060562  0.062688    67766400
4 1986-03-19  0.060031  0.061625  0.059500  0.061093    47894400

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9958 entries, 0 to 9957
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9958 non-null   datetime64[ns]
 1   Close   9958 non-null   float64
 2   High    9958 non-null   float64
 3   Low     9958 non-null   float64
 4   Open    9958 non-null   float64
 5   Volume  9958 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 466.9 KB

In [13]:
train_size = int(0.8 * len(df))
train_df, test_df = df.iloc[:train_size], df.iloc[train_size:]

In [14]:
test_df.to_csv('./Microsoft_stock_test_data.csv', index=False)

In [15]:
test_df.head()

           Date      Close       High        Low       Open    Volume
7966 2017-10-17  71.137779  71.165290  70.826056  71.027763  16824000
7967 2017-10-18  71.156136  71.376176  70.936095  71.211144  13300700
7968 2017-10-19  71.431145  71.449478  70.917709  71.119415  15092800
7969 2017-10-20  72.256325  72.403023  71.715391  71.807074  22866400
7970 2017-10-23  72.274666  72.742250  72.210487  72.421357  20627200

In [17]:
test_df.tail()

           Date       Close        High         Low        Open    Volume
9953 2025-09-15  515.359985  515.469971  507.000000  508.790009  17143800
9954 2025-09-16  509.040009  517.229980  508.600006  516.880005  19711900
9955 2025-09-17  510.019989  511.290009  505.929993  510.619995  15816600
9956 2025-09-18  508.450012  513.070007  507.660004  511.489990  18913700
9957 2025-09-19  517.929993  519.299988  510.309998  510.559998  52371500

In [16]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1992 entries, 7966 to 9957
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1992 non-null   datetime64[ns]
 1   Close   1992 non-null   float64
 2   High    1992 non-null   float64
 3   Low     1992 non-null   float64
 4   Open    1992 non-null   float64
 5   Volume  1992 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 93.5 KB